<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ListingService.Domain\ListingService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="14.0.0" />
      <PackageReference Include="MediatR" Version="12.5.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.5" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.5" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.5" />
      <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    </ItemGroup>

</Project>
