<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\SynopsisSI.Shared.Events\SynopsisSI.Shared.Events.csproj" />
      <ProjectReference Include="..\OrderService.Domain\OrderService.Domain.csproj" />
    </ItemGroup>

</Project>
