<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ListingService.Application\ListingService.Application.csproj" />
      <ProjectReference Include="..\ListingService.Domain\ListingService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AWSSDK.S3" Version="4.0.0.6" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.5" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.5" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.5" />
      <PackageReference Include="MongoDB.EntityFrameworkCore" Version="9.0.0" />
    </ItemGroup>

</Project>
