<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <AssemblyName>SynopsisSI.Services.ListingService.API</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.1" />
        <PackageReference Include="AWSSDK.S3" Version="4.0.0.6" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.4.1" />
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
        <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.2" />
        <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ListingService.Application\ListingService.Application.csproj" />
      <ProjectReference Include="..\ListingService.Infrastructure\ListingService.Infrastructure.csproj" />
    </ItemGroup>

</Project>
